app/models.py
#Importing flask and render_template
from flask import Flask, render_template, request, redirect, url_for
from datetime import datetime
from . import db
from flask_login import UserMixin

''''@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))'''

#Creating table that holds information
class Blogpost(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50))
    subtitle = db.Column(db.String(50))
    author = db.Column(db.String(20))
    content = db.Column(db.String(500))
    date_posted = db.Column(db.DateTime)

#Creating table that holds information
class Users(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50))
    username = db.Column(db.String(10))
    password = db.Column(db.String(20))
    password = db.Column(db.String(20))
    

app.py
#Importing flask and render_template
from flask import Flask, render_template, request, redirect, url_for
from datetime import datetime
#Importing Flask-SQLAlchemy for database setup.

from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

#Setting Database location
SQLALCHEMY_DATABASE_URI='postgresql+psycopg2://karis:Kar!s123@localhost/blog'
db = SQLAlchemy(app)



if __name__ == '__main__':
    app.run(debug=True)

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()

def create_app(config_state):
    app = Flask(__name__)
    app.config.from_object(config_options[config_state])


    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/__pycache__/main/views.py
#Importing flask and render_template
from flask import Flask, render_template, request, redirect, url_for
from datetime import datetime

#Importing Flask-SQLAlchemy for database setup.
from flask_sqlalchemy import SQLAlchemy

#Route for index...views
@app.route('/')
def index():
    posts = Blogpost.query.order_by(Blogpost.date_posted.desc()).all()

    return render_template('index.html', post=posts)

#Route for about
@app.route('/about')
def about():
    return render_template('about.html')

#Route for post
@app.route('/post/<int:post_id>')
def post(post_id):
    post = Blogpost.query.filter_by(id=post_id).one()

    return render_template('post.html', post=post)

#Route for add
@app.route('/add')
def add():
    return render_template('add.html')

#Route for Adding Post
@app.route('/addpost', methods=['POST'])
def addpost():
    title = request.form['title']
    subtitle = request.form['subtitle']
    author = request.form['author']
    content = request.form['content']

    post = Blogpost(title=title, subtitle=subtitle, author=author,content=content, date_posted=datetime.now())

    db.session.add(post)
    db.session.commit()

    return redirect(url_for('index'))

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from . import views

app/main/views.py
#Importing flask and render_template
from flask import Flask, render_template, request, redirect, url_for
from datetime import datetime
from . import main
from ..models import Blogpost 
#Importing Flask-SQLAlchemy for database setup.
from flask_sqlalchemy import SQLAlchemy
from flask_login import login_required
from .. import db

#Route for index...views
@main.route('/')
def index():
    posts = Blogpost.query.order_by(Blogpost.date_posted.desc()).all()

    return render_template('index.html', posts=posts)

#Route for about
@main.route('/about')
def about():
    return render_template('about.html')

#Route for post
@main.route('/post/<int:post_id>')
def post(post_id):
    post = Blogpost.query.filter_by(id=post_id).one()

    return render_template('post.html', post=post)

#Route for add
@main.route('/add')
def add():
    return render_template('add.html')

#Route for Adding Post
@main.route('/addpost', methods=['POST'])
def addpost():
    title = request.form['title']
    subtitle = request.form['subtitle']
    author = request.form['author']
    content = request.form['content']

    post = Blogpost(title=title, subtitle=subtitle, author=author,content=content, date_posted=datetime.now())

    db.session.add(post)
    db.session.commit()


    return redirect(url_for('main.index'))

app/templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title></title>

  <!-- Bootstrap core CSS -->
  <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{{ url_for('static', filename='font-awesome.min.css') }}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
    rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->

  <link href="{{ url_for('static', filename='personal-blog.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='templates.css') }}" rel="stylesheet">
  

</head>

<body>

  <!-- Navigation  Bar-->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">View Blogs</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fa fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.add') }}">Add Post</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead"style="background-image: url('{{ url_for('static', filename='about-bg.jpg') }}')">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">What I do?</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Hi I'm Collins</p>
        <p>Welcome to Travel blog! Want to know where I am currently exploring and where I am headed next? Follow Blog for details.</p>
        <p>Before I had my own adventure travel blog, I was inspired to explore the world after reading other people’s travel blogs online. Travel blogs are a wonderful source for cool ideas & advice if you’re planning a trip somewhere</p>
        <p>Yes. Traveling on your own can be dangerous. This is true for some destinations but generally, I tend to believe it is not!</p>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p class="copyright text-muted">Copyright &copy; Collins 2018</p>
        </div>
      </div>
    </div>
  </footer>
  
</body>

</html>

app/templates/add.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Travel Blog </title>

  <!-- Bootstrap core CSS -->
  <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{{ url_for('static', filename='font-awesome.min.css') }}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
    rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{{ url_for('static', filename='personal-blog.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='templates.css') }}" rel="stylesheet">

</head>

<body>

  <!-- Navigation  Bar-->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">View Blogs</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fa fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.add') }}">Add Post</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->

<!-- Image Header -->

  <header class="masthead"style="background-image: url('{{ url_for('static', filename='blog-bg.jpg') }}')">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Add Post</h1>
            <span class="subheading">Create blog post.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <form name="addForm" id="addForm" method="POST" action="{{ url_for('.addpost') }}" novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Title</label>
              <input type="text" class="form-control" placeholder="Title" name="title" id="title" required data-validation-required-message="Please enter a title.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Subtitle</label>
              <input type="text" class="form-control" placeholder="Subtitle" name="subtitle" id="subtitle" required data-validation-required-message="Please enter your email address.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Author</label>
              <input type="text" class="form-control" placeholder="Author" name="author" id="author" required data-validation-required-message="Please enter your phone number.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Blog Content</label>
              <textarea rows="5" class="form-control" placeholder="Blog content" name="content" id="content" required data-validation-required-message="Please enter a message."></textarea>
              <p class="help-block text-danger"></p>
      <div class="form-group floating-label-form-group controls">
                <label>ADD IMAGE:</label>
              </div>      </div>
          </div>
          <br>

            <!-- Choose Image Button -->
            <p class="drag-and-drop position-relative">
              <div class="form-group floating-label-form-group controls">
                <label>ADD IMAGE:</label>
              </div>
                <input accept=".gif,.jpeg,.jpg,.png," type="file" multiple="multiple"></input>
            </p>

          <div id="success"></div>
          <div class="form-group">
            <button type="submit" class="btn btn-secondary" id="sendMessageButton">Send</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p class="copyright text-muted">Copyright &copy; Collins 2018</p>
        </div>
      </div>
    </div>
  </footer>
</body>

</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <meta name="description" content="">
  <meta name="author" content="">

  <title>Travel Blog - View Blogs!</title>

  <!-- Bootstrap core CSS -->

  <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">
 

  <!-- Custom fonts for this template -->

  <link href="{{ url_for('static', filename='font-awesome.min.css') }}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
    rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->

  <link href="{{ url_for('static', filename='personal-blog.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='templates.css') }}" rel="stylesheet">

</head>

<body>

  <!-- Navigation Bar -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('.index') }}">View Blogs</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">

        Menu
        <i class="fa fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.add') }}">Add POST</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->

  <header class="masthead"style="background-image: url('{{ url_for('static', filename='home-bg.jpg') }}')">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Travel</h1>
            <span class="subheading">Live With No Excuses Travel With No Regrets!</span>
          </div>
        </div>
      </div>
    </div>
  </header>


  <!-- Main Content -->

  <div class="container">
    <div class="row">
      <div class="post-preview">
      </div>
      <div class="col-lg-8 col-md-10 mx-auto">
         {% for post in posts %}
        <div class="post-preview">
          <a href="{{ url_for('.post', post_id=post.id) }}">
            <h2 class="post-title"style="color:#0D8499;">
               &#8680  {{ post.title }} 
            </h2>
            <h3 class="post-subtitle">
              {{ post.subtitle }}
            </h3>
          </a>
          <p class="post-meta">Posted by {{ post.author }} on {{ post.date_posted.strftime('%B %d, %Y') }}</p>

          <textarea name="comment[body]" id="new_comment_field" placeholder="Leave a comment" aria-label="Comment body" class="form-control input-contrast comment-form-textarea js-comment-field js-task-list-field js-quick-submit js-size-to-fit js-suggester-field js-quote-selection-target js-session-resumable js-saved-reply-shortcut-comment-field"></textarea>
          <button type="submit" class="btn btn-primary" data-disable-with="" data-disable-invalid="">
            Comment
          </button>

        </div>
        {% endfor %}
        <hr>
      </div>
    </div>
  </div>


  <!--Default Content  -->
  
  <div class="container">
    <div class="row">
      </div>
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
            <h2 class="post-title"style="color:#0D8499;" >
               &#8680 AIRBNB HOST
            </h2>
            <h3 class="post-subtitle">
               Wouldn’t it be great if you had something that could help you get closer to an early retirement? Something that could help
              you make extra money to put away towards a life of financial independence? If you own a house or an apartment, you could
              become an Airbnb host and list out the entire place when you are away or just a room when you're there. Airbnb properties
              are now in 191 countries. And did you know that the fastest growing demographic of Airbnb hosts are women over 60? Not to
              mention they are getting some of the highest 5-star reviews.
            </h3>
          </a>
          <p class="post-meta">Posted by Collins on April 19th 2016</p>

          <textarea name="comment[body]" id="new_comment_field" placeholder="Leave a comment" aria-label="Comment body" class="form-control input-contrast comment-form-textarea js-comment-field js-task-list-field js-quick-submit js-size-to-fit js-suggester-field js-quote-selection-target js-session-resumable js-saved-reply-shortcut-comment-field"></textarea>
          <button type="submit" class="btn btn-primary" data-disable-with="" data-disable-invalid="">
            Comment
          </button>

        </div>

            <div class="post-preview">
              <h2 class="post-title"style="color:#0D8499;">
               &#8680 TRAVEL APPS
              </h2>
              <h3 class="post-subtitle">
                 Travel apps can really enhance the experience and ease of travel. These travel apps are the ones you use when you're on
                your trip, not for the pre-planning. There are tons of travel apps to help you find the best airfare or the best hotel. These
                apps represent the most useful when you walk out your door to the airport until you come home. These are the top ten I use
                on just about every trip I take. Not all are free but when it comes to a good app, I have no problem paying for it. Most
                apps are cheap so splurge a little when you find something you really like. Paying for an app may just remove those annoying
                ads that pop up or give you that extra functionality that makes the app so much more useful. I bolded either free or the
                price depending on what I use.

              </h3>
              </a>
              <p class="post-meta">Posted by Collins on April 18th 2016</p>

              <textarea name="comment[body]" id="new_comment_field" placeholder="Leave a comment" aria-label="Comment body" class="form-control input-contrast comment-form-textarea js-comment-field js-task-list-field js-quick-submit js-size-to-fit js-suggester-field js-quote-selection-target js-session-resumable js-saved-reply-shortcut-comment-field"></textarea>
              <button type="submit" class="btn btn-primary" data-disable-with="" data-disable-invalid="">
                Comment
              </button>

            </div>

              <div class="post-preview">
                <h2 class="post-title"style="color:#0D8499;">
                 &#8680 UBER (FREE)
                </h2>
                <h3 class="post-subtitle">
                   I think just about everyone has heard of Uber. But did you know that Uber operates Internationally? Uber is almost always
                  cheaper than a taxi and can be so much easier to get. I also like that I don’t have to worry about having money in the currency
                  of the country I just arrived in. No money exchanges hands. It’s all done via your credit card. I used Uber not only in the
                  US but also Ecuador and Ireland. Have Uber installed on your phone and set up with a credit card before you travel. The only
                  thing that bothers me is that some Uber drivers feel they need to call you. It’s happened to me only in big cities in the
                  US. For me, it’s a problem because I don’t have a US phone. I really don’t know why they want to call. Most of the time it’s
                  to tell you they are on their way and the car they are driving. But I already know that because the app tells me. It’s just
                  one of those little things that bug me. But overall, Uber is my number one option for local travel when traveling.
              
                </h3>
                </a>
                <p class="post-meta">Posted by Collins on April 17th 2016</p>

                <textarea name="comment[body]" id="new_comment_field" placeholder="Leave a comment" aria-label="Comment body" class="form-control input-contrast comment-form-textarea js-comment-field js-task-list-field js-quick-submit js-size-to-fit js-suggester-field js-quote-selection-target js-session-resumable js-saved-reply-shortcut-comment-field"></textarea>
                <button type="submit" class="btn btn-primary" data-disable-with="" data-disable-invalid="">
                  Comment
                </button>

              </div>

        <hr>
      </div>
    </div>
  </div>


  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p class="copyright text-muted">Copyright &copy; Collins 2018</p>
        </div>
      </div>
    </div>
  </footer>

 </body>

</html>

app/templates/post.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Travel Blog  Start Bloging</title>

  <!-- Bootstrap core CSS -->

  <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">

  <!-- Custom fonts for this template -->

  <link href="{{ url_for('static', filename='font-awesome.min.css') }}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
    rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->

  <link href="{{ url_for('static', filename='personal-blog.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='personal-blog.min.css') }}" rel="stylesheet">

</head>

<body>

  <!-- Navigation  Bar-->

  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">View Blogs</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fa fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.add') }}">Add Post</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->

  <!-- Image Header -->

  <header class="masthead"style="background-image: url('{{ url_for('static', filename='post-bg.jpg') }}')">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>{{ post.title }}</h1>
            <h2 class="subheading">{{ post.subtitle }}</h2>
            <span class="meta">Posted by {{ post.author }} on {{ post.date_posted.strftime('%B %d, %Y') }}</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->

  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          {{ post.content|safe }}
        </div>
      </div>
    </div>
  </article>

  <hr>

  <!-- Footer -->
  
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p class="copyright text-muted">Copyright &copy; Collo 2018</p>
        </div>
      </div>
    </div>
  </footer>

</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - Start Bootstrap Theme</title>

    <!-- Bootstrap CSS -->
    <link href="{{url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{url_for('static', filename='font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{{url_for('static', filename='personal-blog.min.css') }}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('index') }}">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('index') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('about') }}">About</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead"style="background-image: url('{{ url_for('static', filename='home-bg.jpg') }}')">

      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Clean Blog</h1>
              <span class="subheading">A Blog Theme by Start Bootstrap</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                Man must explore, and this is exploration at its greatest
              </h2>
              <h3 class="post-subtitle">
                Problems look mighty small from 150 miles up
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on September 24, 2018</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
              </h2>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on September 18, 2018</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                Science has not yet mastered prophecy
              </h2>
              <h3 class="post-subtitle">
                We predict too much for the next year and yet far too little for the next ten.
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on August 24, 2018</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                Failure is not an option
              </h2>
              <h3 class="post-subtitle">
                Many say exploration is part of our destiny, but it’s actually our duty to future generations.
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on July 8, 2018</p>
          </div>
          <hr>
          <!-- Pager -->
          <div class="clearfix">
            <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
          </div>
        </div>
      </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->


    <!-- Custom scripts for this template -->
    <script src="{{url_for('static', filename='personal-blog.min.js') }}"></script>

  </body>

</html>